### ISSUE TITLE
Proposal: support tsconfig "compilerOptions.types"

### ISSUE THREAD

**Issue by ewgenius** [twa-dev/types#1]
@ArthurStam thanks for great twa libraries, good job 👍 

Just a small proposal - what do you think about switching from `index.ts` to `index.d.ts` and providing global namespace augmentation out of the box?

With that changes it would be possible to add twa types with just tsconfig setting `compilerOptions.types`:

<img width="1152" alt="CleanShot 2022-08-15 at 22 04 00@2x" src="https://user-images.githubusercontent.com/827338/184699940-81c5e738-8a84-4e5e-8c15-1112f02c1046.png">

**Comment by ArthurStam** [comment]
@ewgenius I think that maybe it's not a good idea to pollute global namespace in this package. We have publish another package: https://github.com/twa-dev/sdk, check it out:

```js
import WebApp from '@twa-dev/sdk';

WebApp.showAlert('Hey there!');
```

It allows you to work with SDK and don't think about `window` at all.

**Comment by ewgenius** [comment]
That makes sense, thanks!
